base_url = "https://eugene-babichenko.github.io"
compile_sass = true
build_search_index = false
theme = "anemone"
generate_feeds = true
feed_filenames = ["feed.xml"]
title = "Eugene Babichenko"
description = "Eugene's personal blog"
minify_html = true
author = "Eugene Babichenko"

[markdown]
highlight_code = true

[extra]
list_pages = true
header_nav = [
    { url = "/", name_en = "/home/" },
    { url = "/blog", name_en = "/blog/" },
    { url = "https://github.com/eugene-babichenko", name_en = "/github/" },
    { url = "https://standwithukraine.com.ua/", name_en = "/\U0001f1fa\U0001f1e6 Support Ukraine/" }
]
