base_url = "https://eugene-babichenko.github.io"
compile_sass = true
build_search_index = false
theme = "anemone"
generate_feeds = true
feed_filenames = ["feed.xml"]

[markdown]
highlight_code = true

[extra]
list_pages = true
header_nav = [
    { url = "/", name_en = "/home/" },
    { url = "/blog", name_en = "/blog/" },
    { url = "https://github.com/eugene-babichenko", name_en = "/github/" }
]
