on:
  push:
    branches:
      - master

name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build and deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download --repo 'getzola/zola' --pattern '*-x86_64-unknown-linux-gnu.tar.gz'
          tar -xvzf *-x86_64-unknown-linux-gnu.tar.gz
          ./zola build
          cd public
          touch .nojekyll
          git init
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions-bot@users.noreply.github.com'
          git add -A
          git commit -m 'deploy'
          remote="https://$GITHUB_ACTOR:$GH_TOKEN@github.com/eugene-babichenko/eugene-babichenko.github.io"
          git push --force $remote 'master:gh-pages'
